name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test against Rails main
        if: ${{ matrix.ruby >= 3.2 }}
        run: |
          bundle exec appraisal rails-main bundle install
          bundle exec appraisal rails-main rake test

      - name: Test against Rails 8.0
        if: ${{ matrix.ruby >= 3.1 }}
        run: |
          bundle exec appraisal rails-8-0 bundle install
          bundle exec appraisal rails-8-0 rake test

      - name: Test against Rails 7.1
        run: |
          bundle exec appraisal rails-7-1 bundle install
          bundle exec appraisal rails-7-1 rake test

  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.3]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake lint
